### ISSUE TITLE
From 9.3.0 installing 9.1.2 using prefab.js9.js9core.install(branch='9.1.2') fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#117]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu

#### Detailed description

In order to install Zero-OS Orchestrator we need first a 9.1.2 version of JumpScale that will host the Orchestrator. Installing 9.1.2 from a JumpScale environment running 9.3.0 through prefab fails.

#### Steps to reproduce

```python
import os
app_id = os.environ["APP_ID"]
secret = os.environ["SECRET"]
url = "se-gen-1.demo.greenitglobe.com"
client = j.clients.openvcloud.get(app_id, secret, url)
account = client.account_get("Account_of_Yves", create=False) 
vdc = account.space_get("Orchestrator", "se-gen-1")

path = os.path.expanduser("~/.ssh/mykey")
j.clients.ssh.load_ssh_key(path=path, create_keys=True)

orchestrator_host = vdc.machine_get("orchestrator", sshkeyname="mykey", create=True, disksize=50, sizeId=3)

prefab = orchestrator_host.prefab
prefab.js9.js9core.install(branch='9.1.2')
```

#### Relevant stacktraces

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 prefab.js9.js9core.install(branch='9.1.2')

/opt/code/github/jumpscale/prefab9/modules/js9/Prefabjs9Core.py in install(self, reset, branch)
     29         self.logger.info("js9_install")
     30         self.core.run(
---> 31             "export JS9BRANCH=%s;ZInstall_host_js9" % branch, profile=True)
     32
     33         self.prefab.runtimes.pip.install("Cython,asyncssh,numpy,tarantool")

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py in run(self, cmd, die, debug, checkok, showout, profile, replaceArgs, shell, env, timeout)
   1267
   1268         rc, out, err = self.executor.execute(
-> 1269             cmd, checkok=checkok, die=die, showout=showout, env=env, timeout=timeout)
   1270
   1271         # out = self._clean(out)

/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py in execute(self, cmds, die, checkok, showout, timeout, env, asScript, hide)
    130
    131         rc, out, err = self.sshclient.execute(
--> 132             cmds2, die=die, showout=showout)
    133
    134         if hide is False:

/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py in execute(self, cmd, showout, die)
    287         if rc and die:
    288             raise j.exceptions.RuntimeError(
--> 289                 "Cannot execute (ssh):\n%s\noutput:\n%serrors:\n%s" % (cmd, out.getvalue(), err.getvalue()))
    290
    291         return rc, out.getvalue(), err.getvalue()

RuntimeError: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;export JS9BRANCH=9.1.2;ZInstall_host_js9"
output:
[+] ZInstall_host_base already installed
[+] loading or updating jumpscale source code (branch:9.1.2)
[+] Checking if https://github.com/jumpscale/core9/tree/9.1.2 exists
[+] get code https://github.com/jumpscale/core9.git (9.1.2)
 [+] clone
Cloning into 'core9'...
[+] Checking if https://github.com/jumpscale/lib9/tree/9.1.2 exists
[+] get code https://github.com/jumpscale/lib9.git (9.1.2)
 [+] clone
Cloning into 'lib9'...
[+] Checking if https://github.com/jumpscale/prefab9/tree/9.1.2 exists
[+] get code https://github.com/jumpscale/prefab9.git (9.1.2)
 [+] clone
Cloning into 'prefab9'...
[+] update jumpscale code done
[+] clean previous js9 install
[+] install js9
/opt/code/github/jumpscale/core9 ~

**** ERRORLOG ****
Obtaining file:///opt/code/github/jumpscale/core9
Collecting GitPython>=2.1.3 (from JumpScale9==9.1.2)
  Downloading GitPython-2.1.7-py2.py3-none-any.whl (446kB)
Collecting click>=6.7 (from JumpScale9==9.1.2)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting colored_traceback (from JumpScale9==9.1.2)
  Downloading colored-traceback-0.3.0.tar.gz
Collecting colorlog>=2.10.0 (from JumpScale9==9.1.2)
  Downloading colorlog-3.1.0-py2.py3-none-any.whl
Collecting httplib2>=0.10.3 (from JumpScale9==9.1.2)
  Downloading httplib2-0.10.3.tar.gz (204kB)
Collecting ipython>=6.0.0 (from JumpScale9==9.1.2)
  Downloading ipython-6.2.1-py3-none-any.whl (745kB)
Collecting libtmux>=0.7.1 (from JumpScale9==9.1.2)
  Downloading libtmux-0.7.7.tar.gz
Collecting netaddr>=0.7.19 (from JumpScale9==9.1.2)
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
Collecting path.py>=10.3.1 (from JumpScale9==9.1.2)
  Downloading path.py-10.5-py2.py3-none-any.whl
Collecting pystache>=0.5.4 (from JumpScale9==9.1.2)
  Downloading pystache-0.5.4.tar.gz (75kB)
Collecting python-dateutil>=2.6.0 (from JumpScale9==9.1.2)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
Collecting pytoml>=0.1.12 (from JumpScale9==9.1.2)
  Downloading pytoml-0.1.14.tar.gz
Collecting toml (from JumpScale9==9.1.2)
  Downloading toml-0.9.3.1.tar.gz
Collecting redis>=2.10.5 (from JumpScale9==9.1.2)
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
Collecting requests>=2.13.0 (from JumpScale9==9.1.2)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting future>=0.16.0 (from JumpScale9==9.1.2)
  Downloading future-0.16.0.tar.gz (824kB)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from JumpScale9==9.1.2)
Collecting watchdog (from JumpScale9==9.1.2)
  Downloading watchdog-0.8.3.tar.gz (83kB)
Collecting msgpack-python (from JumpScale9==9.1.2)
  Downloading msgpack-python-0.4.8.tar.gz (113kB)
Collecting gitdb2>=2.0.0 (from GitPython>=2.1.3->JumpScale9==9.1.2)
  Downloading gitdb2-2.0.3-py2.py3-none-any.whl (63kB)
Collecting pygments (from colored_traceback->JumpScale9==9.1.2)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
Collecting simplegeneric>0.8 (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading simplegeneric-0.8.1.zip
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
Collecting jedi>=0.10 (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading jedi-0.11.0-py2.py3-none-any.whl (146kB)
Collecting traitlets>=4.2 (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB)
Collecting pickleshare (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading pexpect-4.3.0-py2.py3-none-any.whl (55kB)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.5/dist-packages (from ipython>=6.0.0->JumpScale9==9.1.2)
Collecting decorator (from ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading decorator-4.1.2-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.6.0->JumpScale9==9.1.2)
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0->JumpScale9==9.1.2)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0->JumpScale9==9.1.2)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests>=2.13.0->JumpScale9==9.1.2)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
Collecting idna<2.7,>=2.5 (from requests>=2.13.0->JumpScale9==9.1.2)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Requirement already satisfied: PyYAML>=3.10 in /usr/lib/python3/dist-packages (from watchdog->JumpScale9==9.1.2)
Collecting argh>=0.24.1 (from watchdog->JumpScale9==9.1.2)
  Downloading argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog->JumpScale9==9.1.2)
  Downloading pathtools-0.1.2.tar.gz
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython>=2.1.3->JumpScale9==9.1.2)
  Downloading smmap2-2.0.3-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting parso==0.1.0 (from jedi>=0.10->ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading parso-0.1.0-py2.py3-none-any.whl (89kB)
Collecting ipython-genutils (from traitlets>=4.2->ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=6.0.0->JumpScale9==9.1.2)
  Downloading ptyprocess-0.5.2-py2.py3-none-any.whl
Building wheels for collected packages: colored-traceback, httplib2, libtmux, pystache, pytoml, toml, future, watchdog, msgpack-python, simplegeneric, pathtools
  Running setup.py bdist_wheel for colored-traceback: started
  Running setup.py bdist_wheel for colored-traceback: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/11/43/8f/1b6b7b25c8930ede2f8afb2e73d3d052b73f24e62eb3cfb711
  Running setup.py bdist_wheel for httplib2: started
  Running setup.py bdist_wheel for httplib2: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ca/ac/5f/749651f7925b231103f5316cacca82a487810c22d30f011c0c
  Running setup.py bdist_wheel for libtmux: started
  Running setup.py bdist_wheel for libtmux: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/dd/ac/75/02359074e255283b2b31a92b886abdd04743687ffb63bcac7a
  Running setup.py bdist_wheel for pystache: started
  Running setup.py bdist_wheel for pystache: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/cb/7f/2c/c0cbdfc2fc99bebbe38218110b53ba8282c4ad9f7cfaa2bc21
  Running setup.py bdist_wheel for pytoml: started
  Running setup.py bdist_wheel for pytoml: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f1/20/a0/4f8e1596f2cf1e44452c94e68468830f55af346a7d50be7df7
  Running setup.py bdist_wheel for toml: started
  Running setup.py bdist_wheel for toml: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/70/be/69/bb6fce595610d1fa64fad91f430be17fd59b00df0c536c0f1c
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for watchdog: started
  Running setup.py bdist_wheel for watchdog: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/3c/9c/be/e82ae5a37c19baf8abe88623d1f47d2d502bed7b54d4f34740
  Running setup.py bdist_wheel for msgpack-python: started
  Running setup.py bdist_wheel for msgpack-python: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2c/e7/e7/9031652a69d594665c5ca25e41d0fb3faa024e730b590e4402
  Running setup.py bdist_wheel for simplegeneric: started
  Running setup.py bdist_wheel for simplegeneric: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/7b/31/08/c85e74c84188cbec6a6827beec4d640f2bd78ae003dc1ec09d
  Running setup.py bdist_wheel for pathtools: started
  Running setup.py bdist_wheel for pathtools: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/60/0d/2a/ffe065d190b580be6af9a862c68ed6a8a89c1778bd5c7ba7b8
Successfully built colored-traceback httplib2 libtmux pystache pytoml toml future watchdog msgpack-python simplegeneric pathtools
Installing collected packages: smmap2, gitdb2, GitPython, click, pygments, colored-traceback, colorlog, httplib2, simplegeneric, wcwidth, prompt-toolkit, parso, jedi, decorator, ipython-genutils, traitlets, pickleshare, ptyprocess, pexpect, ipython, libtmux, netaddr, path.py, pystache, python-dateutil, pytoml, toml, redis, urllib3, chardet, certifi, idna, requests, future, argh, pathtools, watchdog, msgpack-python, JumpScale9
  Found existing installation: urllib3 1.13.1
    Uninstalling urllib3-1.13.1:
      Successfully uninstalled urllib3-1.13.1
  Found existing installation: chardet 2.3.0
    Uninstalling chardet-2.3.0:
      Successfully uninstalled chardet-2.3.0
  Found existing installation: idna 2.0
    Uninstalling idna-2.0:
      Successfully uninstalled idna-2.0
  Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
  Running setup.py develop for JumpScale9
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to JumpScale9.egg-info/requires.txt
    writing top-level names to JumpScale9.egg-info/top_level.txt
    writing JumpScale9.egg-info/PKG-INFO
    writing dependency_links to JumpScale9.egg-info/dependency_links.txt
    reading manifest file 'JumpScale9.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'JumpScale9.egg-info/SOURCES.txt'
    running build_ext
    Creating /usr/local/lib/python3.5/dist-packages/JumpScale9.egg-link (link to .)
    Adding JumpScale9 9.1.2 to easy-install.pth file
    Installing js9 script to /usr/local/bin
    Installing js9_code script to /usr/local/bin
    Installing js9_docker script to /usr/local/bin
    Installing js9_docs script to /usr/local/bin

    Installed /opt/code/github/jumpscale/core9
    Running post install task
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/jumpscale/core9/setup.py", line 88, in <module>
        'cmds/js9_docs',
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/code/github/jumpscale/core9/setup.py", line 34, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
        func(*args)
      File "/opt/code/github/jumpscale/core9/setup.py", line 9, in _post_install
        from JumpScale9 import j  # here its still the boostrap JumpScale9
      File "/opt/code/github/jumpscale/core9/JumpScale9/__init__.py", line 100, in <module>
        j.do.initEnv()
      File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 2138, in initEnv
        self.linkJSCommandsToSystem()
      File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 2142, in linkJSCommandsToSystem
        self.symlinkFilesInDir(src, "/usr/local/bin", delete=True, includeDirs=False, makeExecutable=True)
      File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 1238, in symlinkFilesInDir
        listSymlinks=True)
      File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 1432, in listFilesInDir
        case_sensitivity=case_sensitivity, exclude=exclude, followSymlinks=followSymlinks, listSymlinks=listSymlinks)
      File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 1492, in _listAllInDir
        dircontent = self._listInDir(path)
      File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 1354, in _listInDir
        path)
    RuntimeError: Specified path: /root/gig/code/github/jumpscale/core9/cmds/ does not exist in system.fs.listDir
    config set me:{'fullname': 'Kristof De Spiegeleer', 'loginname': 'despiegk'}
    config set email:{'smtp_server': '', 'from': 'info@incubaid.com', 'smtp_port': 443}
    config set redis:{'addr': 'localhost', 'port': 6379}
    config set grid:{'gid': 0, 'nid': 0}
    config set dirs:{'DATADIR': '/root/gig/var/data', 'VARDIR': '/root/gig/var/', 'BASEDIR': '/root/gig/gig', 'LIBDIR': '/root/gig/gig/lib', 'LOGDIR': '/root/gig/var/log', 'BUILDDIR': '/root/gig/var/build', 'BINDIR': '/root/gig/gig/bin', 'HOMEDIR': '/root', 'TMPDIR': '/tmp', 'JSAPPSDIR': '/root/gig/gig/apps', 'CFGDIR': '/root/gig/var/cfg', 'TEMPLATEDIR': '/root/gig/gig/templates', 'CODEDIR': '/root/gig/code'}
    config set git:{'js': {'branch': 'master', 'url': 'https://github.com/Jumpscale/core9.git'}, 'ays': {'branch': 'master', 'url': 'https://github.com/Jumpscale/ays9.git'}}
    config set system:{'debug': True, 'container': False, 'autopip': False, 'readonly': False}
    config set ssh:{'SSHKEYNAME': 'id_rsa'}

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/code/github/jumpscale/core9/

[-] something went wrong: Could not install core9 of js9


errors:
cp: cannot stat '//opt/code/github/jumpscale/core9/mascot': No such file or directory
 ((type:runtime.error)
```

**Comment by ahussein** [comment]
I would say this is defiantly not supported scenario.
