### ISSUE TITLE
Capacity parser fail when dmidecode doesn't specify the numbe of thread per cpu

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#279]
```
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/node/node.py", line 64, in _register
    self.node_sal.capacity.register()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/Capacity.py", line 77, in register
    data = self.get(farmer_id)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/Capacity.py", line 63, in get
    cru=report.CRU,
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/capacity/parser.py", line 94, in CRU
    unit += int(cpu.get('thread_nr', 0))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by zaibon** [comment]
Although this is easy to fix, it raises an other problem.
the thread_nr is actually use to compute the cpu resource unit (CRU), without it, the node will be marked as having no CRU at all.
We could use some different dmidecode output so we could harden the parser to handle as much different hardware as possible
