### ISSUE TITLE
itsyouonline client broken

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/lib9#296]
#### Installation information

- jumpscale version:  2bc5e01
- operating system: linux

#### Detailed description
itsyouonline client broken in master

#### Relevant stacktraces
```python
Traceback (most recent call last):
  File "create_chain.py", line 45, in <module>
    if node.is_running():
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/sal/Node.py", line 314, in is_running
    state = self.client.ping()
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 138, in ping
    return self.json('core.ping', {})
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 126, in json
    result = self.sync(command, arguments, tags=tags, id=id)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 110, in sync
    response = self.raw(command, arguments, tags=tags, id=id)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/Client.py", line 226, in raw
    self._redis.rpush('core:default', json.dumps(payload))
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/Client.py", line 75, in _redis
    self._jwt_expire_timestamp = j.clients.itsyouonline.jwt_expire_timestamp(password)
  File "/usr/lib/python3/dist-packages/js9.py", line 841, in itsyouonline
    from JumpScale9Lib.clients.itsyouonline.IYOFactory import IYOFactory as IYOFactory
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/itsyouonline/IYOFactory.py", line 4, in <module>
    from .IYOClient import IYOClient
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/itsyouonline/IYOClient.py", line 5, in <module>
    from JumpScale9Lib.clients.itsyouonline.generated.client import Client
ImportError: No module named 'JumpScale9Lib.clients.itsyouonline.generated'
[Wed30 09:01] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - No module named 'JumpScale9Lib.clients.itsyouonline.generated'
```

**Comment by FastGeert** [comment]
picnic
