### ISSUE TITLE
Error happened due to the expire value of key defined in `set` method

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/lib9#51]
## Issue 
Error happened due to the expire value of key defined in `set` method in `lib9/JumpScale9Lib/data/key_value_store/store.py` is set to 0 instead of None (maybe due to changes to update in redis library) 

## Error 
```
[Thu17 09:25] - AtYourServiceRepo.py:40  :j.atyourservice.server         - ERROR    - can't load repo at /opt/code/
github/jumpscale/ays9/tests/sample_repo4/: invalid expire time in set
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 37, in _load
    repo = AtYourServiceRepo(path, loop=self._loop)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/AtYourServiceRepo.py", line 142, in __init__
    j.atyourservice.server._loadActionBase()
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/AtYourServiceFactory.py", line 133, in _loadActionBase
    action_code_model.save()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/capnp/ModelBase.py", line 130, in save
    self.collection._db.set(self.key, buff)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/key_value_store/store.py", line 248, in set
    self._set(key, data, expire=expire)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/data/key_value_store/redis_store.py", line 49, in _set
    return self.redisclient.set(self._getKey(key), val, ex=expire)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: invalid expire time in set

```

## Software Version 
```
aioredis==0.3.3
hiredis==0.2.0
redis==2.10.6
```

**Comment by rkhamis** [comment]
Indeed that's because of the newer version of py-redis. See [changelog](https://github.com/andymccurdy/redis-py/blob/master/CHANGES#L8)

**Comment by john-kheir** [comment]
Verified
